### ISSUE TITLE
NC relay/switch

### ISSUE THREAD

**Issue by danielsza** [Yurik72/ESPHap#109]
is it possible using the switch example to switch the relay from using NO to NC?

**Comment by Yurik72** [comment]
I think small changes will help you  ,just change (inverse) value written to gpio
void set_switch(bool val){
   Serial.println(String("set_switch:")+String(val?"True":"False")); 
//  digitalWrite(relay_gpio, val?HIGH:LOW);  
 digitalWrite(relay_gpio, val?LOW:HIGH);
