### ISSUE TITLE
multi accessory

### ISSUE THREAD

**Issue by Julius971** [Yurik72/ESPHap#110]
Hi, can you upload examples for scenarios, where i have multiple outlets ore something like that.

**Comment by Julius971** [comment]
And in addition to this, is it possible to combine a light and another one, even a simpler toggle device would be awesome

**Comment by Yurik72** [comment]
Examples of multiaccessory looks like this
https://github.com/Yurik72/ESPHap/blob/master/examples/EspHap_RGB_Motion/EspHap_RGB_Motion.ino

for first(main acessory)
you call 
hapservice= hap_add_lightbulb_service("Led",led_callback,(void*)&led_gpio);
for any nexts light bulb or other devices you should call like this
hapservice2=  hap_add_lightbulb_service_as_accessory("Led2",led_callback2,(void*)&led_gpio2);  // change param or duplicate them


As well this is a liitle mentioned in readme
