### ISSUE TITLE
Close received, client will be disconnected on ESP-01S

### ISSUE THREAD

**Issue by alisadeghy** [Yurik72/ESPHap#111]
Hi again!
I tried different devices and almost never had this problem again as I mentioned in #105 but recently I bought a bunch of ESP-01s modules and this encountered this error again.
When I use ESP-01 everything works properly but on all ESP-01S modules I get this error!
What should I change in the code? I tried to change identity led pin since the 01S has different LEDs but it didn't help.

>>> HomeKit: Calculating public key result 0
>>> HomeKit: arduino_homekit_preinit success
>>> HomeKit: WiFiServer receives a new client (current 0, max 8)
>>> HomeKit: Got new client connection: local 192.168.1.110:5556, remote 192.168.1.104:61630
>>> HomeKit: [Client 1073701420] Got client content from the cache 0
>>> HomeKit: [Client 1073701420] new client accepted
>>> HomeKit: [Client 1073701420] Pair Setup Step 1/3
>>> HomeKit: [Client 1073701420] Connection: close received, client will be disconnected
>>> HomeKit: [Client 1073701420] Closing client connection
>>> HomeKit: Free saved_preinit_pairing_context
>>> HomeKit: [Client 0] Clear the pairing context
>>> HomeKit: [Client 0] client content free
>>> HomeKit: Preinit pairing context
>>> HomeKit: Using user-specified password: 111-11-111
>>> HomeKit: Free heap: 20424
>>> HomeKit: Calculating public key len=384
>>> HomeKit: Calculating public key result 0
>>> HomeKit: arduino_homekit_preinit success
>>> HomeKit: WiFiServer receives a new client (current 0, max 8)
>>> HomeKit: Got new client connection: local 192.168.1.110:5556, remote 192.168.1.104:61631
>>> HomeKit: [Client 1073701420] Got client content from the cache 0
>>> HomeKit: [Client 1073701420] new client accepted
>>> HomeKit: [Client 1073701420] Pair Setup Step 1/3
>>> HomeKit: [Client 1073701420] Connection: close received, client will be disconnected
>>> HomeKit: [Client 1073701420] Closing client connection
>>> HomeKit: Free saved_preinit_pairing_context
>>> HomeKit: [Client 0] Clear the pairing context
>>> HomeKit: [Client 0] client content free
>>> HomeKit: Preinit pairing context
>>> HomeKit: Using user-specified password: 111-11-111
>>> HomeKit: Free heap: 20152
>>> HomeKit: Calculating public key len=384
>>> HomeKit: Calculating public key result 0
>>> HomeKit: arduino_homekit_preinit success
>>> HomeKit: WiFiServer receives a new client (current 0, max 8)
>>> HomeKit: Got new client connection: local 192.168.1.110:5556, remote 192.168.1.104:61633
>>> HomeKit: [Client 1073701420] Got client content from the cache 0
>>> HomeKit: [Client 1073701420] new client accepted
>>> HomeKit: [Client 1073701420] Pair Setup Step 1/3
>>> HomeKit: [Client 1073701420] Connection: close received, client will be disconnected
>>> HomeKit: [Client 1073701420] Closing client connection
>>> HomeKit: Free saved_preinit_pairing_context
>>> HomeKit: [Client 0] Clear the pairing context
>>> HomeKit: [Client 0] client content free
>>> HomeKit: Preinit pairing context
>>> HomeKit: Using user-specified password: 111-11-111
>>> HomeKit: Free heap: 20336
>>> HomeKit: Calculating public key len=384
>>> HomeKit: Calculating public key result 0
>>> HomeKit: arduino_homekit_preinit success

**Comment by Yurik72** [comment]
In 99% is wellknown problem 
Please have a look #52, #54, #42
 
According to read me 
! Note for ESP8266 boards select lwIP Variant :v2 High bandwidth. Device behaviours is more stable especially in pairing process
