### ISSUE TITLE
WiFi Config at Runtime

### ISSUE THREAD

**Issue by JohnWickham** [Yurik72/ESPHap#22]
It seems this library doesn’t include a way of configuring the WiFi network at runtime using the web server method that others do. Has anyone integrated a library for this successfully? I’m having trouble getting any of them to work.

**Comment by Yurik72** [comment]
Example  [EspHapAdvancedLed](https://github.com/Yurik72/ESPHap/tree/master/examples/EspHapAdvancedLed) contains usage of [WiFiManager](https://github.com/tzapu/WiFiManager), which allows to setup WiFI at Runtime

**Comment by JohnWickham** [comment]
Right you are, thanks again for the tip!
