### ISSUE TITLE
Use of this in Commercial Products will require MFI Licence ?

### ISSUE THREAD

**Issue by arihantdaga** [Yurik72/ESPHap#23]
Please forgive me if i am confused. 
But i saw that the other sdk from espressif has a different commercial version, and that can be used for commercial version and for that mfi license is compulsory. 
I wonder if we can use this library in commercial products or not without mfi license?

**Comment by Yurik72** [comment]
Hi, the one of the significant libraries which are used for this implementation is [wolfssl](https://github.com/wolfSSL/wolfssl), whisch  is under GPL-2.0 License, therefore my understanding, you are not permitted to use my implementation for commercial purpose.
