### ISSUE TITLE
Include examples in library.json for reference in Arduino IDE

### ISSUE THREAD

**Issue by ESPdude** [Yurik72/ESPHap#27]
It would be cool if you'd include the examples within Arduino IDE.

With a simple 

`"examples": "examples/*/*.ino"`

statement in file library.json, users would be able to open the example projects right within Arduino.

<img width="646" alt="Bildschirmfoto 2020-11-11 um 13 53 43" src="https://user-images.githubusercontent.com/17149672/98814221-ab399680-2425-11eb-94c5-8495f81c496b.png">

<img width="880" alt="Bildschirmfoto 2020-11-11 um 13 53 10" src="https://user-images.githubusercontent.com/17149672/98814256-b5f42b80-2425-11eb-90e0-b5156797c6a2.png">

**Comment by Yurik72** [comment]
merged pull request
