### ISSUE TITLE
Multiple wifi

### ISSUE THREAD

**Issue by skrew** [Yurik72/ESPHap#35]
Hi,

Thanks for this amazing library

I have 2 questions:

- It is possible to define 2 or 3 wifi so i can move with my homekit object ?
- I have an object with a strip led, the integration with homekit works fine. BTW i would like to add some leds FX, so is there a way to add a list of "actions" or something like that ?

**Comment by Yurik72** [comment]
Hi,

1)  There is not in the scope of the current library. By default, ESP32 able to internally keep only one connection. Therefore you are not limited to use any third party library, they are using different approaches to store credentials on the SPIFFS or EEPROM 

2) At the moment NOT. I undesrtand your request, you want to manage any effects and modes as well. There is only one possibility from Apple to show custom list in the TV Menu ( :)) accessory. Furthemore I want to implement that , there is a not big deal, but question is my time. If you will do that, i will appreciate a pull request. Library inside contains all definitions for that.
