### ISSUE TITLE
wolfssl.h: No such file or directory

### ISSUE THREAD

**Issue by yepkevin612** [Yurik72/ESPHap#38]
i got extract either [wolfSSL_3_13_0.rar] to Arduino library but still cannot compile the example.
C:\Users\user\Documents\libraries\ESPHap-master\aa.c:2:21: fatal error: wolfssl.h: No such file or directory
 #include <wolfssl.h>

**Comment by Yurik72** [comment]
According readme : Extract the content of wolfSSL_3_13_0.rar to a Arduino library folder named "wolfssl".
Means that, ....\Arduino\libraries\wolfSSL, should contain wolfssl.h  file. Probably you extracted into subfolder. Please double check
