### ISSUE TITLE
Error in homeintegration.c 

### ISSUE THREAD

**Issue by seamaster101** [Yurik72/ESPHap#4]
so finally I figured out why the humidity never worked correctly!
in file homeintegration.c you had:
`
homekit_service_t* hap_add_humidity_service(const char* szname){
    
	homekit_service_t*service=NEW_HOMEKIT_SERVICE(TEMPERATURE_SENSOR, .characteristics=(homekit_characteristic_t*[]) {
	            NEW_HOMEKIT_CHARACTERISTIC(NAME, szname),
	            NEW_HOMEKIT_CHARACTERISTIC(CURRENT_RELATIVE_HUMIDITY, 0),
	            NULL`

it should've been:
`
homekit_service_t* hap_add_humidity_service(const char* szname){
    
	homekit_service_t*service=NEW_HOMEKIT_SERVICE(HUMIDITY_SENSOR, .characteristics=(homekit_characteristic_t*[]) {
	            NEW_HOMEKIT_CHARACTERISTIC(NAME, szname),
	            NEW_HOMEKIT_CHARACTERISTIC(CURRENT_RELATIVE_HUMIDITY, 0),
	            NULL`
**Now I have Temperature and humidity showing together, with proper icons and proper values!** it only took me 3 days. LOL
please correct in your library and close this case.
there is still remaining issue with the serial monitor overflowing with 
`>> HomeKit: [Client 1073691748] Got characteristic 1.10 change event
>>> HomeKit: [Client 1073691748] Got characteristic 1.13 change event`
but I will open new case for that one

**Comment by Yurik72** [comment]
Ok thanks for testing and correct hints
