### ISSUE TITLE
Got hardware watchdog restart on NodeMCU

### ISSUE THREAD

**Issue by 97mik** [Yurik72/ESPHap#45]
Got hardware watchdog restart on NodeMCU when **crypto_srp_compute_key** on **Pair Setup Step 2/3**

**Comment by Yurik72** [comment]
Is not reproducable in any existing my devices
Please make sure:
1. Use latest version or version tagged v1.0.7
2. You have not a problem with power supply/caable (it can happen, due to the power eating at this moment)

Than give me feedback

**Comment by 97mik** [comment]
1.0.7 release works fine, thanks
