### ISSUE TITLE
Прошивка на 4 датчика температуры на SONOFF с интеграцией Homekit

### ISSUE THREAD

**Issue by SokolAndriy** [Yurik72/ESPHap#53]
Здравствуйте!

Заинтересовал проект умного дома на Homekit, но везде есть только один вариант одно устройство один датчик, А у меня есть контроллеры которые имеют по 4 и более датчиков (DS18B20). Если все это попробовать интегрировать в homekt, то придется ставить на каждый датчик отдельное устройство, что не есть удобно в моем случае.

Если это возможно просьба помочь в написании такой прошивки.
Заранее благодарю.

С уважением, Андрей

**Comment by Yurik72** [comment]
Example https://github.com/Yurik72/ESPHap/tree/master/examples/EspHap_Thermo_N_Sensors

Contains basis how to setup N sensors on the one board, Hovewer it's not completelly finished due to the  right devices handling, which is out of the scope current library
