### ISSUE TITLE
Error compiling with #define HOMEKIT_DUBUG on ESP32

### ISSUE THREAD

**Issue by eford321** [Yurik72/ESPHap#58]
Getting the following error when compiling with #define HOMEKIT_DUBUG on ESP32 using c822ae8.
...
Arduino: 1.8.13 (Mac OS X), Board: "WEMOS D1 MINI ESP32, 80MHz, Default, 240MHz (WiFi/BT), 921600"

In file included from /Users/evan/Documents/Arduino/libraries/ESPHap/server.c:41:0:
/Users/evan/Documents/Arduino/libraries/ESPHap/server.c: In function 'homekit_server_on_update_characteristics':
/Users/evan/Documents/Arduino/libraries/ESPHap/debug.h:19:29: error: expected ';' before 'printf'
 #define DEBUG(message, ...) printf(">>> %s: " message "\n", __func__, ##__VA_ARGS__)
                             ^
/Users/evan/Documents/Arduino/libraries/ESPHap/debug.h:39:23: note: in expansion of macro 'DEBUG'
 #define DEBUG_HEAP()  DEBUG("Free heap: %d", esp_get_free_heap_size());
                       ^
/Users/evan/Documents/Arduino/libraries/ESPHap/server.c:2258:5: note: in expansion of macro 'DEBUG_HEAP'
     DEBUG_HEAP();
     ^
Multiple libraries were found for "WiFi.h"
 Used: /Users/evan/Library/Arduino15/packages/esp32/hardware/esp32/1.0.5/libraries/WiFi
 Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi
exit status 1
Error compiling for board WEMOS D1 MINI ESP32.

**Comment by Yurik72** [comment]
Fixed
