### ISSUE TITLE
Home Integration: homekit_is_paired 0

### ISSUE THREAD

**Issue by oxbown** [Yurik72/ESPHap#6]
Hi! Thank you so much for this library!
I´m using ESPHap with an esp8266 (Wemos D1). I got it working, I can add the accessory to the Home app (sometimes fails as you said in the description), but when I´ve got the accessory paired if I restart the esp8266 (press the restart button) the device not run as before. It got a new ID and starts in "pairing mode".

In the serial plot "Home Integration: homekit_is_paired 0" appears when I restart.
What's going on with this?
Thank you!

**Comment by Yurik72** [comment]
Hi , there are two modes of device , you are right
1. before pairing: device is waiting for pairing
2. After pairing: devices is not introduce pairing info and simple connect to apple
Yo wrote:
In the serial port "Home Integration: homekit_is_paired 0" appears when I restart.

This is my mistake on ESP8266. It's always shows 0, independently from pairing status
I did changes on the latest commit to show right status

If you have other wondering or question  or device not working properly please attach full logs
