### ISSUE TITLE
EspHapLed8266 crashes when removing an accessory

### ISSUE THREAD

**Issue by AGRO666** [Yurik72/ESPHap#76]
I tried different versions - 1.0.9, 1.0.7, ESP8266 board library version 2.6.3, 2.7.3, 2.7.4.
I use Arduino version 1.8.13, patched versions of wolfSSL 3.13.0
Maybe some development environment settings are required?
Board - Wemos D1 mini

13:05:05.738 -> >>> HomeKit: [Client 1073700348] Remove Pairing
13:05:05.738 -> 
13:05:05.738 -> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
13:05:05.738 -> 
13:05:05.738 -> Exception (28):
13:05:05.738 -> epc1=0x402165d9 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000034 depc=0x00000000
13:05:05.772 -> 
13:05:05.772 -> >>>stack>>>
13:05:05.772 -> 
13:05:05.772 -> ctx: cont
13:05:05.772 -> sp: 3fff1b00 end: 3fff1de0 offset: 0190
13:05:05.772 -> 3fff1c90:  0000002c 3fff5e44 3fff0968 4021bc69  
13:05:05.772 -> 3fff1ca0:  00000000 3fff09b1 3fff1d00 00000000  
13:05:05.772 -> 3fff1cb0:  3fff41f4 0000002c 3fff0968 40218f02  
13:05:05.772 -> 3fff1cc0:  00000004 00000000 0000000a 00000000  
13:05:05.772 -> 3fff1cd0:  3fff421f 00030000 3fff0968 4021d3a0  
13:05:05.772 -> 3fff1ce0:  3fff421f 00030000 3fff4d94 40205168  
13:05:05.805 -> 3fff1cf0:  3fff417e 3fff06a8 00000000 00000000  
13:05:05.805 -> 3fff1d00:  00000000 00000000 00000000 3fff4220  
13:05:05.805 -> 3fff1d10:  000000a2 00000000 00000047 00000000  
13:05:05.805 -> 3fff1d20:  00000030 3fff41d9 3fff1e28 00000003  
13:05:05.805 -> 3fff1d30:  00000001 3fff23a8 3fff5f90 00000000  
13:05:05.805 -> 3fff1d40:  3fff0968 3fff417e 00000c28 4021bf95  
13:05:05.805 -> 3fff1d50:  000000a2 3fff416c 3fff08d8 3fff1e28  
13:05:05.839 -> 3fff1d60:  000000a2 3fff416c 3fff08d8 3fff1e28  
13:05:05.839 -> 3fff1d70:  3fffdad0 00000000 3fff23a8 3fff1e28  
13:05:05.839 -> 3fff1d80:  3fffdad0 3fff0968 3fff416c 4021c43b  
13:05:05.839 -> 3fff1d90:  00000000 3fff08d4 3fff0d58 4021d6d6  
13:05:05.839 -> 3fff1da0:  00000000 00000000 3fff1de8 4021d814  
13:05:05.839 -> 3fff1db0:  3fffdad0 00000000 3fff1de8 40216d1c  
13:05:05.839 -> 3fff1dc0:  3fffdad0 00000000 3fff1de8 4021eab4  
13:05:05.872 -> 3fff1dd0:  feefeffe feefeffe 3ffe886c 40100cbd  
13:05:05.872 -> <<<stack<<<
13:05:05.872 -> 
13:05:05.872 -> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
13:05:05.872 -> 
13:05:05.872 ->  ets Jan  8 2013,rst cause:2, boot mode:(3,6)

**Comment by Yurik72** [comment]
Please check last commit, I fixed an issue
Thanks
