### ISSUE TITLE
Changing Default Password

### ISSUE THREAD

**Issue by oxbown** [Yurik72/ESPHap#8]
Hi!
Can we add a void in homeintegration.c to change the default password? So if we call in the .ino file the Hap function we can change the default password.
Are there any limitations on changing the password from 111-11-111 to any other (pairing limitations etc...)?

**Comment by Yurik72** [comment]
I have introduced new function
void hap_set_device_password(char* szpwd);
There are not limitation, but in my plan to continue working on QR initialization and generation

**Comment by oxbown** [comment]
I can confirm that "hap_set_device_password" works!!

**Comment by alisadeghy** [comment]
Would you please tell me how to use this function? What should I change and how it reflects on pairing code?
