### ISSUE TITLE
Platformio compilation

### ISSUE THREAD

**Issue by beckmx** [Yurik72/ESPHap#90]
I was trying to migrate a project from arduino to platformio, but I am getting this issue and no matter what I do, looks like the wolfssl or wolfSSL definition cannot be found not in the libs or as a dependency lib, any suggestions where else to look for?
```
.pio/libdeps/odroid_esp32/ESPHap/aa.c:2:10: fatal error: wolfssl.h: No such file or directory

*****************************************************************
* Looking for wolfssl.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:wolfssl.h"
* Web  > https://platformio.org/lib/search?query=header:wolfssl.h
*
*****************************************************************

 #include <wolfssl.h>
          ^~~~~~~~~~~
compilation terminated.
*** [.pio/build/odroid_esp32/lib933/ESPHap/aa.c.o] Error 1
.pio/libdeps/odroid_esp32/ESPHap/crypto.c:6:10: fatal error: wolfssl.h: No such file or directory

```

**Comment by Yurik72** [comment]
Hi I did migration some of the project, please have a look example  https://github.com/Yurik72/IoTManager

You should have wolfssl under lib folder

**Comment by beckmx** [comment]
Just as a complementary doc, I needed to include these flags to make it compilable:
```
-DESP32
	-DARDUINO
	-Wno-error=maybe-uninitialized
	-Wno-error=uninitialized
	-Wno-error=implicit-function-declaration
	-Wno-error=misleading-indentation
	-Wno-error=return-type
	-Wno-error=parentheses
	-Wno-error=stringop-overflow
	-Wno-error=comment
```
And modified the include:
`#include <hapfilestorage/hapfilestorage.hpp>`

Looks like it was using the backward slash in some of the examples
