### ISSUE TITLE
Unable to compile EspHap_WindowCovering for generic ESP8266

### ISSUE THREAD

**Issue by hhoef** [Yurik72/ESPHap#94]
I get the error:
EspHap_WindowCovering:65:1: error: 'esp_timer_create_args_t' does not name a type
 esp_timer_create_args_t _timerConfig;
 ^
EspHap_WindowCovering:66:1: error: 'esp_timer_handle_t' does not name a type
 esp_timer_handle_t _timer=NULL;
 ^
I use Arduine IDE 1.8.13

Hubert

**Comment by Yurik72** [comment]
I have chganged implementation for ESP8266 based on the Ticker
